### ISSUE TITLE
BAC-113 ⁃ publish and deploy chart to a staging environment

### ISSUE THREAD

**Issue by alika** [samsung-cnct/chart-technical-on-boarding#5]
- [x] version chart appropriately for alpha/master and stable/version-tagged builds
   - alpha/master == last tagged version + commit count after last tagged version
   - stable/version-tag == tagged version + 0
- [x] publish this chart to [quay application registry][1] _alpha_ channel on commits to master
- [x] publish this chart to [quay application registry][1] _stable_ channel on tagged versions
- [x] deploy chart to a _staging_ environment on commits to master

[1]: https://quay.io/application/samsung_cnct/technical-on-boarding-chart

**Comment by cwazy1** [comment]
➤ Alika Larsen commented:

Work is being done on [PR#6](https://github.com/samsung-cnct/chart-technical-on-boarding/pull/6). Once the PR is approved and merged back to master, this task will be complete.
