### ISSUE TITLE
BAC-111 ⁃ Deploy latest version of app/chart to production via gitlab

### ISSUE THREAD

**Issue by alika** [samsung-cnct/chart-technical-on-boarding#7]
┆Attachments: <a href="https:&#x2F;&#x2F;samsung-cnct.atlassian.net&#x2F;secure&#x2F;attachment&#x2F;15100&#x2F;t.o.b-rbac.yaml">t.o.b-rbac.yaml</a> | <a href="https:&#x2F;&#x2F;samsung-cnct.atlassian.net&#x2F;secure&#x2F;attachment&#x2F;15101&#x2F;t.o.b-rbac+%28a7175cee-6b31-4ed2-9d10-3b5c5f62e2ac%29.yaml">t.o.b-rbac (a7175cee-6b31-4ed2-9d10-3b5c5f62e2ac).yaml</a>

**Comment by cwazy1** [comment]
➤ Patrick Christopher commented:

step 1.  talk to Mark about getting programmatic access built into gitlab

**Comment by cwazy1** [comment]
➤ Patrick Christopher commented:

Sent four questions, three of which I care about for this ticket:

  1. what is our production cluster target?  cyklops-superior, the CI cluster
  2. what is the formal way to ask for access?  I think I will need to file an epic for this
  3. what can we, ft-penguin, do for this particular issue?  <No answer yet>
  4. How do we want to manage these credentials going forward?  I will not report on this question any further in this issue.  It is an important consideration but not one that needs to be answered to get this application to production.  It should come up in the ticket answer \#2

**Comment by cwazy1** [comment]
➤ Patrick Christopher commented:

created namespace, user, kubeconfig and RBAC objects for this.  also installed tiller.

next:  how to re-init client side for helm and create secret in gitlab

**Comment by cwazy1** [comment]
➤ Patrick Christopher commented:

[^t.o.b-rbac.yaml] 

attached file 't.o.b-rbac.yaml' contains the kubernetes objects created for this issue.

helm command:
KUBECONFIG=cyklops-superior.kubeconfig HELM_HOME=./ helm init --tiller-namespace technical-on-boarding --service-account sa-admin

the 'sa-admin' ServiceAccount is created in the linked document.

**Comment by cwazy1** [comment]
➤ Patrick Christopher commented:

Next step:

  * wait for [staging CD PR ](https://github.com/samsung-cnct/chart-technical-on-boarding/pull/6) to be merged then template the production CD portion off of what staging does.

Moving this back to ToDo as BLOCKED until above PR is merged.

**Comment by cwazy1** [comment]
➤ Patrick Christopher commented:

staging PR is merged.  now to get the production dunnered more better.

**Comment by cwazy1** [comment]
➤ Patrick Christopher commented:

PR to deploy to production has been opened.  when complete I will attempt to deploy the latest tag pushed to github.

if that deploy works I will update the pretty url (technical-on-boarding.kubeme.io) to point to the new application.

huh, I wonder if there's a kube-lego running in the production cluster.  I forgot to check until right now.

**Comment by cwazy1** [comment]
➤ Patrick Christopher commented:

notes:

  * deployed to production (v1.1.6), need to verify deploy still
  * going to deploy again with new DNS entry:  technical-on-boarding.cnct.io instead of technical-on-boarding.kubeme.io
  * had to update the RBAC yaml, was misconfigured
  * typo, had to make the name of the subject for the RoleBinding match the name of the service account

**Comment by cwazy1** [comment]
➤ Patrick Christopher commented:

end of week notes:

  * created https://technical-on-boarding.cnct.io/ and it now resolves
  * it worked!  will test again after shutting down tob.kubeme.io, make sure nothing is still linking over to there
  * should be ready to close this out first thing monday.
  * for now, I've redirected tob.kubeme.io -> tob.cnct.io.  should be fine!

**Comment by cwazy1** [comment]
➤ Patrick Christopher commented:

ToReview:

  * https://technical-on-boarding.cnct.io works
  * https://technical-on-boarding.kubeme.io doesn't work
  * technical on boarding application is running in superior cluster
  * technical on boarding application was deployed via gitlab ci
    * https://git.cnct.io/common-tools/samsung-cnct_chart-technical-on-boarding/pipelines/2434
